import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import {
  ArrowDownRight, ArrowRight, BookOpen, BriefcaseBusiness, CheckCircle2,
  ChevronDown, CircleHelp, FileText, GraduationCap, Handshake, HeartHandshake,
  Mail, MessageCircle, Network, Search, ShieldCheck, Sprout, Users, Wallet,
  Workflow, Wrench,
} from "lucide-react";

type PageKey = "about" | "how" | "help" | "terms" | "privacy";

const motionClass = "animate-[page-rise_.65s_cubic-bezier(.2,.75,.25,1)_both]";
const cardClass = "group rounded-3xl border bg-card p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl motion-reduce:transform-none motion-reduce:transition-none";

function PageHero({ eyebrow, title, lead, image = "/images/pages/opportunity-hero.webp" }: { eyebrow: string; title: string; lead: string; image?: string }) {
  return <section className={`relative isolate overflow-hidden rounded-[2rem] border bg-[linear-gradient(120deg,hsl(var(--primary)/.10),transparent_62%)] ${motionClass}`}>
    <div className="grid items-center gap-8 p-7 sm:p-10 lg:grid-cols-[1.1fr_.9fr] lg:p-14">
      <div className="relative z-10">
        <p className="mb-4 inline-flex items-center gap-2 rounded-full border bg-background/80 px-3 py-1 text-xs font-semibold uppercase tracking-[.18em] text-primary"><span className="size-2 rounded-full bg-primary" />{eyebrow}</p>
        <h1 className="max-w-3xl text-4xl font-bold tracking-tight [font-family:var(--font-display)] sm:text-5xl lg:text-6xl">{title}</h1>
        <p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">{lead}</p>
        <div className="mt-7 flex flex-wrap gap-3">
          <Link to="/opportunities" className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground shadow-md transition hover:-translate-y-0.5 hover:shadow-lg motion-reduce:transform-none">Explore opportunities <ArrowRight className="size-4" /></Link>
          <Link to="/help" className="inline-flex items-center gap-2 rounded-full border bg-background px-5 py-3 text-sm font-semibold transition hover:border-primary/40 hover:bg-muted">Visit Help Centre <CircleHelp className="size-4" /></Link>
        </div>
      </div>
      <div className="relative min-h-64 overflow-hidden rounded-[1.5rem] border bg-muted sm:min-h-80">
        <img src={image} alt="Professionals collaborating around meaningful work and economic opportunities" className="absolute inset-0 size-full object-cover transition duration-700 hover:scale-[1.035] motion-reduce:transform-none" onError={(event) => { event.currentTarget.style.display = "none"; }} />
        <div className="absolute inset-0 bg-gradient-to-tr from-primary/35 via-transparent to-background/10" />
        <div className="absolute inset-x-4 bottom-4 rounded-2xl border bg-background/90 p-4 shadow-lg backdrop-blur">
          <p className="text-xs font-semibold uppercase tracking-widest text-primary">UmurimoHub</p>
          <p className="mt-1 text-sm font-medium">Skills. Trusted connections. Productive work.</p>
        </div>
      </div>
    </div>
  </section>;
}

function SectionHeading({ eyebrow, title, lead }: { eyebrow?: string; title: string; lead?: string }) {
  return <div className="mb-7 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{eyebrow ?? "Built for progress"}</p><h2 className="mt-2 text-3xl font-bold tracking-tight [font-family:var(--font-display)] sm:text-4xl">{title}</h2>{lead && <p className="mt-3 leading-7 text-muted-foreground">{lead}</p>}</div>;
}

function Card({ icon: Icon, title, children }: { icon: typeof Users; title: string; children: React.ReactNode }) {
  return <article className={cardClass}><div className="mb-4 inline-flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary transition duration-300 group-hover:rotate-3 group-hover:scale-110 motion-reduce:transform-none"><Icon className="size-5" /></div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{children}</p></article>;
}

function Callout({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="rounded-3xl bg-primary p-7 text-primary-foreground sm:p-10"><h2 className="text-2xl font-bold [font-family:var(--font-display)]">{title}</h2><p className="mt-3 max-w-3xl leading-7 opacity-90">{children}</p><div className="mt-5 flex flex-wrap gap-3"><Link to="/register" className="inline-flex items-center gap-2 rounded-full bg-background px-5 py-3 text-sm font-semibold text-foreground transition hover:-translate-y-0.5">Create your profile <ArrowRight className="size-4" /></Link><Link to="/how-it-works" className="inline-flex items-center gap-2 rounded-full border border-primary-foreground/40 px-5 py-3 text-sm font-semibold transition hover:bg-primary-foreground/10">See how it works</Link></div></div>;
}

const faqs = [
  { q: "How do I get started?", a: "Create an account, complete your profile with accurate information, then explore the opportunities and workflows available to your account." },
  { q: "How do I apply for an opportunity?", a: "Open an opportunity, review its requirements and terms, and follow the application instructions shown on that opportunity." },
  { q: "Are users and experience always verified?", a: "Do not assume every profile claim is independently verified. Look for explicit verification indicators and assess the information available before making a decision." },
  { q: "Does UmurimoHub guarantee a job or payment?", a: "No. The platform helps people connect and manage work-related processes, but does not guarantee work, outcomes, or payment. Parties should agree on clear terms before work begins." },
  { q: "How do referrals work?", a: "Where referrals are available, they can provide context about a connection. A referral is not a guarantee of a person's skills, conduct, or future performance." },
  { q: "How can I protect my account?", a: "Use a strong, unique password where applicable, protect access to your email and sign-in provider, and never share authentication codes or secrets." },
];

function HelpContent() {
  const [query, setQuery] = useState("");
  const [opened, setOpened] = useState<number | null>(0);
  const filtered = useMemo(() => faqs.filter((item) => (item.q + " " + item.a).toLowerCase().includes(query.toLowerCase().trim())), [query]);
  return <div className="mt-14 space-y-14">
    <section><SectionHeading title="Find answers, faster" lead="Search the most common questions about accounts, opportunities, referrals, training, and work-related processes."/><label className="flex max-w-2xl items-center gap-3 rounded-2xl border bg-card px-4 py-3 shadow-sm focus-within:ring-2 focus-within:ring-primary/30"><Search className="size-5 text-muted-foreground"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search help topics…" className="w-full bg-transparent text-sm outline-none" aria-label="Search help topics"/>{query && <button onClick={()=>setQuery("")} className="text-sm text-primary">Clear</button>}</label></section>
    <section><SectionHeading title="Frequently asked questions"/><div className="max-w-4xl space-y-3">{filtered.map((item)=>{const index=faqs.indexOf(item);const active=opened===index;return <article key={item.q} className="overflow-hidden rounded-2xl border bg-card transition-colors hover:border-primary/30"><button className="flex w-full items-center justify-between gap-4 p-5 text-left font-semibold" aria-expanded={active} onClick={()=>setOpened(active?null:index)}>{item.q}<ChevronDown className={`size-5 shrink-0 transition-transform duration-300 ${active?"rotate-180":""}`}/></button><div className={`grid transition-[grid-template-rows] duration-300 ease-out ${active?"grid-rows-[1fr]":"grid-rows-[0fr]"} motion-reduce:transition-none`}><div className="overflow-hidden"><p className="px-5 pb-5 leading-7 text-muted-foreground">{item.a}</p></div></div></article>})}{filtered.length===0 && <div className="rounded-2xl border border-dashed p-8 text-center"><p className="font-semibold">No matching help articles</p><p className="mt-2 text-sm text-muted-foreground">Try another keyword or browse the categories below.</p></div>}</div></section>
    <section><SectionHeading title="Browse by topic"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Card icon={Users} title="Account & profile">Create an account, keep your profile accurate, and manage your professional information.</Card><Card icon={BriefcaseBusiness} title="Opportunities">Understand listings, applications, and how to review requirements before applying.</Card><Card icon={Network} title="Referrals & network">Learn how professional connections and referrals may provide additional context.</Card><Card icon={GraduationCap} title="Training">Explore training and apprenticeship information and application steps.</Card><Card icon={Wallet} title="Contracts & payments">Clarify scope, milestones, payment arrangements, and responsibilities before work begins.</Card><Card icon={ShieldCheck} title="Privacy & security">Read how information is handled and how to protect account access.</Card></div></section>
    <section className="rounded-3xl border bg-muted/40 p-7 sm:p-9"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-bold">Still need help?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Start with the relevant page or use the contact channels officially published by UmurimoHub. We do not display unverified support addresses or phone numbers.</p></div><div className="flex flex-wrap gap-3"><Link to="/terms" className="inline-flex items-center gap-2 rounded-full border bg-background px-4 py-2.5 text-sm font-semibold"><FileText className="size-4"/> Terms</Link><Link to="/privacy" className="inline-flex items-center gap-2 rounded-full border bg-background px-4 py-2.5 text-sm font-semibold"><ShieldCheck className="size-4"/> Privacy</Link></div></div></section>
  </div>;
}

function AboutContent() {
  const values = [{ icon: Users, title: "People and teams", text: "Help people present their capabilities and connect with others who can contribute to meaningful work." },{ icon: BriefcaseBusiness, title: "Real opportunities", text: "Make it easier to discover work and communicate expectations before an engagement begins." },{ icon: GraduationCap, title: "Skills and learning", text: "Support skills development, training, and practical experience as the platform's capabilities evolve." },{ icon: ShieldCheck, title: "Trust through evidence", text: "Use relevant profiles, work records, and available feedback to support better-informed decisions." }];
  const steps = ["Demand","Opportunity","Trusted people & teams","Work","Payment","Verified experience","Reputation","More opportunities","Business growth"];
  return <><section className="mt-16"><SectionHeading title="Why UmurimoHub exists" lead="Valuable skills and real demand do not always find each other easily. Opportunities can be scattered, experience can be hard to demonstrate, and businesses may struggle to identify the right people. UmurimoHub is being built to help connect these parts of the economic journey."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(v=><Card key={v.title} icon={v.icon} title={v.title}>{v.text}</Card>)}</div></section><section className="mt-16"><SectionHeading title="Our mission" lead="Expand access to productive work by connecting skills, trusted relationships, and real economic demand."/><div className="grid gap-4 lg:grid-cols-2"><div className={cardClass}><h3 className="text-xl font-semibold">Our vision</h3><p className="mt-3 leading-7 text-muted-foreground">A more connected economy where people can demonstrate what they can do, businesses can find relevant capabilities, and professional experience can open new doors.</p></div><div className={cardClass}><h3 className="text-xl font-semibold">Our approach</h3><p className="mt-3 leading-7 text-muted-foreground">Build the connections between opportunity, work, payment arrangements, experience, reputation, and growth—while being clear about what is available today and what remains aspirational.</p></div></div></section><section className="mt-16"><SectionHeading title="A connected economic journey" lead="Our long-term model is designed to help successful engagements create a stronger foundation for future opportunities. Each stage depends on the people and agreements involved."/><div className="flex flex-wrap gap-3">{steps.map((step,i)=><div key={step} className="inline-flex items-center gap-2 rounded-2xl border bg-card px-4 py-3 text-sm font-semibold shadow-sm transition hover:-translate-y-1 hover:border-primary/40">{i+1}<span className="text-muted-foreground">/</span>{step}{i<steps.length-1&&<ArrowDownRight className="size-4 text-primary"/>}</div>)}</div></section><section className="mt-16"><SectionHeading title="Who we serve"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={Users} title="Workers">Present your skills, discover opportunities, and build a record of experience.</Card><Card icon={BriefcaseBusiness} title="Businesses">Describe your needs and connect with people or teams with relevant capabilities.</Card><Card icon={Handshake} title="Teams">Bring complementary skills together to pursue projects and shared goals.</Card><Card icon={Sprout} title="Learners & growers">Explore learning, apprenticeship, agriculture, and small-business opportunities where available.</Card></div></section><section className="mt-16"><Callout title="Your skills can create opportunities">Explore the platform, learn how it works, and build a professional profile that accurately reflects what you can contribute.</Callout></section></>;
}

function HowContent() {
  const worker = ["Build a clear profile with accurate skills and experience.","Explore opportunities and read the requirements carefully.","Apply and use referrals where available.","Agree on scope, responsibilities, deadlines, and payment terms.","Deliver the agreed work and follow the completion process.","Keep records of experience and feedback where supported."];
  const business = ["Set up a business profile and describe your needs.","Publish opportunities with clear requirements and expectations.","Review applications and relevant available information.","Agree on deliverables, milestones, timelines, and payment.","Manage the engagement and confirm completion as applicable.","Provide fair, relevant feedback where the feature is available."];
  return <><section className="mt-16"><SectionHeading title="Choose your path" lead="The exact steps available depend on your account and the features currently enabled on the platform."/><div className="grid gap-5 lg:grid-cols-2">{[{title:"For workers",icon:Users,items:worker},{title:"For businesses",icon:BriefcaseBusiness,items:business}].map((path)=><article key={path.title} className={cardClass}><div className="flex items-center gap-3"><path.icon className="size-6 text-primary"/><h3 className="text-xl font-bold">{path.title}</h3></div><ol className="mt-6 space-y-4">{path.items.map((s,i)=><li key={s} className="flex gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">{i+1}</span><span className="pt-1 text-sm leading-6 text-muted-foreground">{s}</span></li>)}</ol></article>)}</div></section><section className="mt-16"><SectionHeading title="More ways to participate"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Card icon={Handshake} title="Teams">Present combined capabilities, discover projects, and agree responsibilities before work begins.</Card><Card icon={GraduationCap} title="Learners & apprentices">Review training opportunities, apply where available, and record completed learning experiences when supported.</Card><Card icon={Sprout} title="Agriculture & MSMEs">Connect sector-specific needs with skills, services, and project work as the relevant platform capabilities become available.</Card></div></section><section className="mt-16"><SectionHeading title="Trust is built through clear expectations"/><div className="grid gap-4 md:grid-cols-3"><Card icon={FileText} title="Agree in advance">Clarify scope, deliverables, deadlines, and responsibilities before work begins.</Card><Card icon={Wallet} title="Understand payment">Agree on payment terms directly and use the available workflow where applicable. The platform does not guarantee payment.</Card><Card icon={CheckCircle2} title="Record outcomes">Follow the applicable completion process. Verification and reputation features depend on the records and controls available.</Card></div></section><section className="mt-16"><Callout title="Ready to take the next step?">Explore current opportunities or visit Help for answers about accounts, applications, training, and work-related processes.</Callout></section></>;
}

const legalSections = {
 terms: [
  ["1. About these terms","These terms describe the basic rules for using UmurimoHub. By accessing or using the platform, you agree to follow applicable terms and laws. If you do not agree, do not use the service."],
  ["2. Accounts and accurate information","Provide information that is accurate to the best of your knowledge, keep it reasonably up to date, and protect your account credentials. Do not impersonate another person or misrepresent qualifications, experience, business status, or identity."],
  ["3. Acceptable use","Do not use the platform for fraud, harassment, unlawful discrimination, spam, unauthorized access, deceptive listings, or other unlawful or harmful activity. Do not attempt to interfere with platform security or operation."],
  ["4. Opportunities and referrals","Opportunity information is supplied by users or other sources and may change. Review requirements and verify relevant details before committing. Referrals can provide context but are not guarantees of ability, conduct, or results."],
  ["5. Work agreements and payments","The parties should clearly agree on scope, deliverables, timing, responsibilities, payment amounts, payment timing, and dispute handling before work begins. Unless expressly stated otherwise, UmurimoHub does not guarantee a job, work quality, payment, or resolution of disputes."],
  ["6. Ratings and experience","Where ratings, work records, or verification features are available, use them honestly and responsibly. A displayed record should not be interpreted as proof beyond the scope of the verification actually performed."],
  ["7. User content and intellectual property","You are responsible for content you submit and must have the rights needed to share it. Do not upload content that violates another person's rights or applicable law. Platform branding and software remain subject to their applicable intellectual-property rights."],
  ["8. Availability and changes","Features may change, be interrupted, or become unavailable. We will not represent a planned feature as available until it is implemented. Nothing in these terms removes rights that cannot legally be excluded."],
  ["9. Suspension and termination","Access may be restricted where reasonably necessary to address security concerns, suspected abuse, legal requirements, or serious breaches. Where appropriate, users should be given information about relevant next steps."],
  ["10. Disputes and applicable law","Users should first communicate clearly and preserve relevant records when a disagreement occurs. The applicable law and formal dispute process must be confirmed for the operating legal entity before this page is treated as final legal advice."],
  ["11. Updates and contact","These terms may be updated as the service develops. The effective date should be updated when substantive changes are made. Use the official contact channel published by UmurimoHub for questions."]
 ],
 privacy: [
  ["1. Scope of this policy","This policy explains how UmurimoHub intends to handle personal information in connection with the platform. It must be read alongside the features and settings actually available in the product."],
  ["2. Information you provide","Depending on how you use the platform, information may include account and profile details, skills, work interests, business or team details, applications, referrals, training activity, messages, and work-related records you submit."],
  ["3. Authentication and technical information","When you sign in using Google or another configured provider, the service receives information needed to authenticate your account, subject to the provider flow and permissions. Technical logs and device information may also be processed where the application and infrastructure generate them."],
  ["4. How information is used","Information may be used to operate accounts, display profiles and opportunities, support applications and connections, provide platform workflows, protect service security, troubleshoot errors, and improve functionality where applicable."],
  ["5. Visibility and sharing","Some profile or business information may be visible to other users according to the product's settings and design. Information may be shared with other participants when needed for an opportunity, application, referral, or work process, and with service providers that support platform operation. Check visibility controls before submitting sensitive information."],
  ["6. Data minimization and sensitive information","Only provide information relevant to using the platform. Do not include passwords, authentication secrets, financial credentials, or unnecessary sensitive personal information in public profile fields or opportunity descriptions."],
  ["7. Retention and deletion","Information may be retained while an account is active and for a period needed for security, operational, legal, or dispute-related purposes. The exact retention schedule and deletion behavior must be confirmed against the deployed system before this policy is finalized."],
  ["8. Security","Reasonable technical and organizational safeguards should be used to protect information. No online system can promise absolute security; protect your sign-in credentials and report suspected unauthorized access through an official contact channel."],
  ["9. Your choices and rights","Depending on applicable law, you may have rights to access, correct, object to, or request deletion of personal information. Available in-product controls and the process for submitting requests should be confirmed before publication."],
  ["10. Cookies, analytics, and third parties","Cookies, analytics, and third-party services should be described according to the integrations actually enabled in the deployed application. This section must be reviewed against production configuration before the policy is considered complete."],
  ["11. Children and eligibility","The platform is intended for people who are legally eligible to use its services. Any age restrictions and processes involving minors must be confirmed against the service's actual rules and applicable law."],
  ["12. Changes and privacy contact","This policy may be updated as the platform changes. The effective date and official privacy contact should be added or updated once the responsible operating entity and contact channel are confirmed."]
 ]
};

function LegalContent({ page }: { page: "terms" | "privacy" }) {
 const sections = legalSections[page];
 return <div className="mt-12 grid gap-8 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border bg-card p-5 lg:sticky lg:top-24"><h2 className="font-semibold">On this page</h2><nav className="mt-3 space-y-1">{sections.map(([title],i)=><a key={title} href={`#legal-${i}`} className="block rounded-lg px-2 py-2 text-sm text-muted-foreground transition hover:bg-muted hover:text-foreground">{title}</a>)}</nav><p className="mt-4 border-t pt-4 text-xs leading-5 text-muted-foreground">Draft for review. Confirm legal entity, applicable law, operational practices, and contact details before treating this page as final.</p></aside><article className="min-w-0 space-y-8">{sections.map(([title,body],i)=><section id={`legal-${i}`} key={title} className="scroll-mt-24 border-b pb-7 last:border-0"><h2 className="text-xl font-bold tracking-tight">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{body}</p></section>)}<p className="rounded-2xl bg-muted p-4 text-sm leading-6 text-muted-foreground">Review status: content framework prepared for product and legal verification. Do not rely on this draft as a substitute for advice from a qualified legal professional.</p></article></div>;
}

export function InfoPage({ page }: { page: PageKey }) {
 const content = {
  about: { eyebrow: "Our purpose", title: "Turning skills and opportunities into meaningful work", lead: "A Rwanda-focused economic opportunity platform connecting people, teams, businesses, and productive work." },
  how: { eyebrow: "A clearer path forward", title: "From opportunity to experience. From experience to growth.", lead: "Understand how profiles, applications, work agreements, and professional experience fit together on UmurimoHub." },
  help: { eyebrow: "Support & guidance", title: "How can we help you move forward?", lead: "Find practical answers about accounts, opportunities, referrals, training, and work-related processes." },
  terms: { eyebrow: "Platform guidelines", title: "Terms of Service", lead: "Understand the responsibilities and expectations that guide use of UmurimoHub." },
  privacy: { eyebrow: "Your information matters", title: "Privacy Policy", lead: "Learn how information is intended to be handled when you use UmurimoHub, and what still requires confirmation before publication." },
 }[page];
 return <main className="container-page py-8 sm:py-12"><PageHero {...content} image={page==="privacy"?"/images/pages/privacy-hero.webp":page==="help"?"/images/pages/help-hero.webp":page==="terms"?"/images/pages/agreements-hero.webp":"/images/pages/opportunity-hero.webp"}/>{page==="about"?<AboutContent/>:page==="how"?<HowContent/>:page==="help"?<HelpContent/>:<LegalContent page={page}/>}<div className="mt-14 flex flex-wrap items-center justify-between gap-4 border-t pt-6 text-sm text-muted-foreground"><p>UmurimoHub · Economic opportunity through trusted connections</p><div className="flex flex-wrap gap-4"><Link to="/about" className="hover:text-primary">About</Link><Link to="/how-it-works" className="hover:text-primary">How it works</Link><Link to="/help" className="hover:text-primary">Help</Link><Link to="/terms" className="hover:text-primary">Terms</Link><Link to="/privacy" className="hover:text-primary">Privacy</Link></div></div></main>;
}
