/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgricultureRouteImport } from './routes/agriculture'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BusinessesIdRouteImport } from './routes/businesses.$id'
import { Route as ContractsIdRouteImport } from './routes/contracts.$id'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as OpportunitiesIdEditRouteImport } from './routes/opportunities.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultureRoute = AgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessesIdRoute = BusinessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessesRoute,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdEditRoute = OpportunitiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OpportunitiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agriculture': typeof AgricultureRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/grow': typeof GrowRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRouteWithChildren
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/teams/$id': typeof TeamsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/opportunities/$id/edit': typeof OpportunitiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agriculture': typeof AgricultureRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/grow': typeof GrowRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRouteWithChildren
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/teams/$id': typeof TeamsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/opportunities/$id/edit': typeof OpportunitiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agriculture': typeof AgricultureRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/grow': typeof GrowRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRouteWithChildren
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/teams/$id': typeof TeamsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/opportunities/$id/edit': typeof OpportunitiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agriculture'
    | '/businesses'
    | '/company'
    | '/dashboard'
    | '/grow'
    | '/help'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/match'
    | '/mcp'
    | '/messages'
    | '/network'
    | '/notifications'
    | '/pricing'
    | '/register'
    | '/settings'
    | '/terms'
    | '/training'
    | '/.well-known/oauth-protected-resource'
    | '/businesses/$id'
    | '/contracts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/teams/$id'
    | '/workers/$id'
    | '/opportunities/'
    | '/teams/'
    | '/workers/'
    | '/.lovable/oauth/consent'
    | '/opportunities/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agriculture'
    | '/businesses'
    | '/company'
    | '/dashboard'
    | '/grow'
    | '/help'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/match'
    | '/mcp'
    | '/messages'
    | '/network'
    | '/notifications'
    | '/pricing'
    | '/register'
    | '/settings'
    | '/terms'
    | '/training'
    | '/.well-known/oauth-protected-resource'
    | '/businesses/$id'
    | '/contracts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/teams/$id'
    | '/workers/$id'
    | '/opportunities'
    | '/teams'
    | '/workers'
    | '/.lovable/oauth/consent'
    | '/opportunities/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agriculture'
    | '/businesses'
    | '/company'
    | '/dashboard'
    | '/grow'
    | '/help'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/match'
    | '/mcp'
    | '/messages'
    | '/network'
    | '/notifications'
    | '/pricing'
    | '/register'
    | '/settings'
    | '/terms'
    | '/training'
    | '/.well-known/oauth-protected-resource'
    | '/businesses/$id'
    | '/contracts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/teams/$id'
    | '/workers/$id'
    | '/opportunities/'
    | '/teams/'
    | '/workers/'
    | '/.lovable/oauth/consent'
    | '/opportunities/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgricultureRoute: typeof AgricultureRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  GrowRoute: typeof GrowRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TrainingRoute: typeof TrainingRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ContractsIdRoute: typeof ContractsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRouteWithChildren
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  TeamsIdRoute: typeof TeamsIdRoute
  WorkersIdRoute: typeof WorkersIdRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agriculture': {
      id: '/agriculture'
      path: '/agriculture'
      fullPath: '/agriculture'
      preLoaderRoute: typeof AgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$id': {
      id: '/businesses/$id'
      path: '/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof BusinessesIdRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id/edit': {
      id: '/opportunities/$id/edit'
      path: '/edit'
      fullPath: '/opportunities/$id/edit'
      preLoaderRoute: typeof OpportunitiesIdEditRouteImport
      parentRoute: typeof OpportunitiesIdRoute
    }
  }
}

interface BusinessesRouteChildren {
  BusinessesIdRoute: typeof BusinessesIdRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesIdRoute: BusinessesIdRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface OpportunitiesIdRouteChildren {
  OpportunitiesIdEditRoute: typeof OpportunitiesIdEditRoute
}

const OpportunitiesIdRouteChildren: OpportunitiesIdRouteChildren = {
  OpportunitiesIdEditRoute: OpportunitiesIdEditRoute,
}

const OpportunitiesIdRouteWithChildren = OpportunitiesIdRoute._addFileChildren(
  OpportunitiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgricultureRoute: AgricultureRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  GrowRoute: GrowRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TrainingRoute: TrainingRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ContractsIdRoute: ContractsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRouteWithChildren,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  TeamsIdRoute: TeamsIdRoute,
  WorkersIdRoute: WorkersIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
